apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-go-basic
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/rh-ee-sconroy-tenant/my-app/devfile-sample-go-basic@sha256:7b6e9fb848f76885640010ccfa7b915b023af017e85348f8b7ac6a0f0c167694
        name: my-go
        resources: {}
status: {}
